# Code Generated by Sidekick is for learning and experimentation purposes only.
from kubernetes import client, config

def check_nodes():
    v1 = client.CoreV1Api()
    print("Node Health:")
    for node in v1.list_node().items:
        name = node.metadata.name
        status = "Ready"
        for condition in node.status.conditions:
            if condition.type == "Ready" and condition.status != "True":
                status = "NotReady"
        print(f" - {name}: {status}")

def check_pods():
    v1 = client.CoreV1Api()
    print("\nPod Health (all namespaces):")
    for pod in v1.list_pod_for_all_namespaces().items:
        name = pod.metadata.name
        ns = pod.metadata.namespace
        phase = pod.status.phase
        print(f" - {ns}/{name}: {phase}")

def main():
    config.load_kube_config()
    check_nodes()
    check_pods()

if __name__ == "__main__":
    main()
